Python/Projeto_Web/controle_de_visitantes/urls.py
from django.contrib import admin
from django.urls import path
from dashboard.views import index
from visitantes.views import registrar_visitantes, informacoes_visitante

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("registrar-visitantes/", registrar_visitantes, name="registrar_visitantes"),
    path("info-visitante/<int:id>", informacoes_visitante, name="informacoes_visitante"),
]

Python/Projeto_Web/hello/urls.py
from django.contrib import admin
from django.urls import path
from index.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index")
]


Python/Projeto_Web/visitantes/models.py
from django.db import models

class Visitante(models.Model):
    nome_completo = models.CharField(
        verbose_name="Nome Completo",
        max_length=255,
    )
    cpf = models.CharField(
        verbose_name="CPF",
        max_length=11, 
        unique=True
    )
    data_nascimento = models.DateField(
        verbose_name="Data de Nascimento",
        auto_now=False,
        auto_now_add=False,
    )
    numero_casa = models.CharField(
        verbose_name="Número da Casa Visitada",
        max_length=255,
    )
    placa_veiculo = models.CharField(
        verbose_name="Placa do Veículo",
        max_length=7, 
        blank=True, 
        null=True,
    )
    hora_chegada = models.DateTimeField(
        verbose_name="Hora de Chegada",
        blank=True, 
        null=True,
        auto_now_add=True,
        )
    hora_saida = models.DateTimeField(
        verbose_name="Hora de Saída",
        blank=True, 
        null=True,
        auto_now=False,
        )
    hora_autorizacao = models.DateTimeField(
        verbose_name="Hora de Autorização",
        blank=True, 
        null=True,
        auto_now=False,
    )
    nome_morador = models.CharField(
        verbose_name="Nome do Morador que autorizou a entrada",
        max_length=255,
        blank=True,
    )
    porteiro_autorizador = models.ForeignKey(
        "porteiros.Porteiro",
        verbose_name="Porteiro que Autorizou a Entrada",
        on_delete=models.PROTECT, 
    )
    STATUS_VISITANTE = [
        ("AGUARDANDO", "Aguardando autorização"),
        ("EM_VISITA", "Em visita"),
        ("FINALIZADO", "Visita finalizada"),
    ]
    status = models.CharField(
        verbose_name = "Status",
        max_length = 20,
        choices = STATUS_VISITANTE,
        default="AGUARDANDO"
    )
    class Meta:
        verbose_name = "Visitante"
        verbose_name_plural = "Visitantes"
        db_table = "visitante"
    
    def __str__(self):
        return self.nome_completo
    
    def get_hora_saida(self):
        if self.hora_saida:
            return self.hora_saida
        return "Horário de saída não registrado"
    
    def get_hora_autorizacao(self):
        if self.hora_autorizacao:
            return self.hora_autorizacao
        return "Horário de Autorização não registrado"
    
    def get_nome_morador(self):
        if self.nome_morador:
            return self.nome_morador
        return "Morador responsável pela autorização não registrado"
    
    def get_placa_veiculo(self):
        if self.placa_veiculo:
            return self.placa_veiculo
        return "Horário de saída não registrado"
    
    def get_status(self):
        if self.status:
            return self.status
        return "Status não registrado"

Python/Projeto_Web/visitantes/forms.py
from django import forms
from visitantes.models import Visitante

class VisitanteForm(forms.ModelForm):
    class Meta:
        model = Visitante
        fields = (
            "nome_completo",
            "cpf",
            "data_nascimento",
            "numero_casa",
            "placa_veiculo",
        )
class AutorizaVisitanteForm(forms.ModelForm):
    morador_responsavel = forms.CharField(required=True)
    class Meta:
        model = Visitante
        fields = [
            "morador_responsavel"
        ]
        error_messages = {
            "morador_responsavel": {
                "required": "Informe o morador responsável"
            }
        }

Python/Projeto_Web/visitantes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib import messages
from visitantes.forms import ( VisitanteForm, AutorizaVisitanteForm )
from visitantes.models import Visitante
from porteiros.models import Porteiro

def registrar_visitantes(request):
    form = VisitanteForm(request.POST)

    if form.is_valid():
        visitante = form.save(commit = False)
        visitante.porteiro_autorizador = Porteiro.objects.get(id=1)
        visitante.save()

        messages.sucess(request, "O Visitante foi cadastrado com sucesso!")
        return redirect("index")

    context = {
        "nome_pagina":"Cadastro de Visitante",
        "form":form,
    }
    return render(request, "visitantes/visitantes.html", context)

def informacoes_visitante(request, id):
    visitante = get_object_or_404(Visitante, id=id)
    
    form = AutorizaVisitanteForm()
    if request.method == "POST":
        form = AutorizaVisitanteForm(request.POST, instance=visitante)

        if form.is_valid():
            visitante = form.save(commit=False)

            visitante.status = "EM_VISITA"
            visitante.horario_autorizacao = timezone.now()

            visitante.save()

            messages.success(request, "Visitante autorizado com sucesso.")
        
        return redirect("index")
    
    context = {
        "nome_pagina":"Informações do Visitante",
        "visitante":visitante, 
        "form":form,
    }

    return render(request, "visitantes/informacoes_visitante.html", context)

Python/Projeto_Web/templates/visitantes/informacoes_visitante.html
{% extends "base.html" %}

{% block content %}
<div class="content">
    <h1>Informações do Visitante:</h1>
    <form style="margin-bottom:10px;">
        <div class="info">
            <p><strong>Nome:</strong> {{ visitante.nome_completo }}</p>
            <p><strong>CPF:</strong> {{ visitante.cpf }}</p>
            <p><strong>Data de Nascimento:</strong> {{ visitante.data_nascimento }}</p>
            <p><strong>Hora de Entrada:</strong> {{ visitante.hora_chegada }}</p>
            <p><strong>Hora de Saída:</strong> {{ visitante.hora_saida }}</p>
            <p><strong>Hora de Autorização:</strong> {{ visitante.hora_autorizacao }}</p>
            <p><strong>Porteiro Responsável:</strong> {{ visitante.porteiro_autorizador }}</p>
            <p><strong>Status do Visitante:</strong> {{ visitante.get_status }}</p>
        </div>
    </form>
    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">                    
                    <form method="post" action="{% url 'informacoes_visitante' visitante.id %}">
                        <div class="form-group">
                            <label for="id_nome_morador" class="col-form-label">Nome do morador responsável por autorizar a entrada do visitante:</label>
                            {{ visitante.nome_morador }}
                        </div>
                        {% csrf_token %}
                        
                        <button type="submit" name="status" value="Finalizado" class="button">
                                <span class="text">Autorizar Entrada</span>
        
                                <span class="icon text-white-50">
                                    <i class="fas fa-door-open"></i>
                                </span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document" style="margin-top: 10px;">
            <form method="post" action="{% url 'informacoes_visitante' visitante.id %}">
                <label>Deseja finalizar a visita?</label>
                {% csrf_token %}
                <button type="submit" name="status" value="Finalizado" class="button">
                        <span class="text">Finalizar Visita</span>

                        <span class="icon text-white-50">
                            <i class="fas fa-door-open"></i>
                        </span>
                </button>
            </form>
        </div>
    </div>
    
</div>

{% endblock %}

Python/Projeto_Web/templates/visitantes/visitantes.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="wrapper">
    <main class="main-content">
        <h1>{{ nome_pagina }}</h1>
        <form method="POST">
            {% csrf_token %}
            <p class="legenda">(*) Campo Obrigatório</p>
            {% for field in form %}
                <div class="form-field">
                    <label>
                        {{ field.label }}
                        {% if field.field.required %} <t class="legenda">*</t> {% endif %}
                    </label>
                    {% render_field field %}
                </div>
            {% endfor %}
            <button type="submit">
                <span>Enviar</span>
            </button>
        </form>
    </main>
</div>
{% endblock content %}